apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-wago
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mreid1-tenant/my-app-4/devfile-sample-go-basic-wago@sha256:67f17df31e26d3538e80701a4873400f83163252c6df4657a63e83efefd18ef1
        name: my-go
        resources: {}
status: {}
